# Vector Structure:
# [age, bmi, income, budget, smoker, hba1c, bp_systolic, has_diabetes, has_hypertension, chronic_count]

INSURANCE_PLANS = [
  {
      "id": 1,
      "name": "Arogya Sanjeevani",
      "insurer": "Star Health",
      "type": "Basic",
      "annual_premium": 3600,
      "coverage": 500000,
      "pre_existing_wait_years": 4,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [25, 22.0, 400000, 500, 0, 5.2, 110, 0, 0, 0], 
      "pros": ["Cheapest premium", "9,800+ hospitals", "No medical test under 45"],
      "cons": ["4-year pre-existing wait", "Low coverage ceiling", "No restore benefit"]
  },
  {
      "id": 2,
      "name": "HDFC Optima Secure",
      "insurer": "HDFC ERGO",
      "type": "Comprehensive",
      "annual_premium": 8200,
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [35, 24.0, 900000, 1000, 0, 5.5, 120, 0, 0, 0],
      "pros": ["Restore benefit", "50% no-claim bonus", "Mental health covered"],
      "cons": ["2-year pre-existing wait", "No OPD cover"]
  },
  {
      "id": 3,
      "name": "Star Health Diabetes Safe",
      "insurer": "Star Health",
      "type": "Comprehensive",
      "annual_premium": 14000,
      "coverage": 500000,
      "pre_existing_wait_years": 0,
      "diabetes_day1": True,
      "hypertension_day1": True,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [45, 28.0, 800000, 1500, 0, 7.5, 135, 1, 1, 1],
      "pros": ["Diabetes covered from Day 1", "Hypertension Day 1", "OPD included"],
      "cons": ["Designed for diabetic patients only", "Lower coverage limit"]
  },
  {
      "id": 4,
      "name": "Niva Bupa ReAssure 2.0",
      "insurer": "Niva Bupa",
      "type": "Comprehensive",
      "annual_premium": 11500,
      "coverage": 2500000,
      "pre_existing_wait_years": 1,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [40, 26.0, 1500000, 1200, 1, 5.8, 128, 0, 0, 1],
      "pros": ["Only 1-year pre-existing wait", "₹25L coverage", "Mental health + unlimited restore"],
      "cons": ["Diabetes still has 1-year wait", "Higher premium"]
  },
  {
      "id": 5,
      "name": "Care Health Care Supreme",
      "insurer": "Care Health",
      "type": "Comprehensive",
      "annual_premium": 9800,
      "coverage": 1500000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 75,
      "ideal_vector": [50, 25.0, 1000000, 1000, 0, 5.6, 125, 0, 0, 1],
      "pros": ["Covers till age 75", "Annual health checkup", "Air ambulance"],
      "cons": ["2-year pre-existing wait", "Complex claims process"]
  },
  {
      "id": 6,
      "name": "LIC Arogya Rakshak",
      "insurer": "LIC",
      "type": "Senior",
      "annual_premium": 18000,
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 45,
      "max_age": 80,
      "ideal_vector": [60, 27.0, 800000, 2000, 0, 6.0, 140, 0, 1, 2],
      "pros": ["Covers till 80", "LIC brand trust", "Critical illness rider"],
      "cons": ["Expensive", "Smaller hospital network", "Not available under 45"]
  },
  {
      "id": 7,
      "name": "Bajaj Allianz Health Guard",
      "insurer": "Bajaj Allianz",
      "type": "Standard",
      "annual_premium": 7200,
      "coverage": 750000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [30, 23.0, 600000, 700, 0, 5.4, 115, 0, 0, 0],
      "pros": ["Affordable", "540 day-care procedures", "Large hospital network"],
      "cons": ["No restore benefit", "Limited OPD"]
  },
  {
      "id": 8,
      "name": "ICICI Lombard Complete Health",
      "insurer": "ICICI Lombard",
      "type": "Standard",
      "annual_premium": 8800,
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [35, 24.0, 800000, 900, 0, 5.5, 120, 0, 0, 0],
      "pros": ["97% claim settlement ratio", "Telemedicine included", "Wellness rewards"],
      "cons": ["Standard 2-year wait", "Nothing exceptional for chronic conditions"]
  },
  {
      "id": 9,
      "name": "Aditya Birla Activ One",
      "insurer": "Aditya Birla",
      "type": "Comprehensive",
      "annual_premium": 13200,
      "coverage": 2000000,
      "pre_existing_wait_years": 1,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [32, 22.0, 1200000, 1300, 0, 5.1, 110, 0, 0, 0],
      "pros": ["Fitness discount up to 10%", "OPD up to ₹15,000/year", "Only 1-year pre-existing wait"],
      "cons": ["Fitness tracking mandatory for discount", "Higher premium"]
  },
  {
      "id": 10,
      "name": "ManipalCigna Prime Senior",
      "insurer": "ManipalCigna",
      "type": "Senior",
      "annual_premium": 22000,
      "coverage": 2500000,
      "pre_existing_wait_years": 0,
      "diabetes_day1": False,
      "hypertension_day1": True,
      "min_age": 56,
      "max_age": 80,
      "ideal_vector": [65, 28.0, 1000000, 2500, 0, 6.2, 145, 0, 1, 2],
      "pros": ["Hypertension from Day 1", "₹25L coverage", "Home care included"],
      "cons": ["Only for 56+", "Diabetes still 1-year wait", "Most expensive"]
  },
  {
      "id": 11,
      "name": "Tata AIG CritiCare",
      "insurer": "Tata AIG",
      "type": "Critical Illness",
      "annual_premium": 6500,
      "coverage": 1500000,
      "pre_existing_wait_years": 4,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 65,
      "ideal_vector": [45, 29.0, 1200000, 800, 1, 5.8, 130, 0, 1, 1],
      "pros": ["Lump sum paid on diagnosis", "Covers income loss during treatment", "Cheap premium"],
      "cons": ["Doesn't pay regular hospital bills", "4-year wait for pre-existing"]
  },
  {
      "id": 12,
      "name": "LIC Tech Term",
      "insurer": "LIC",
      "type": "Term Life",
      "annual_premium": 8000,
      "coverage": 5000000,
      "pre_existing_wait_years": 0,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 18,
      "max_age": 60,
      "ideal_vector": [35, 24.0, 1000000, 800, 0, 5.4, 120, 0, 0, 0],
      "pros": ["Massive ₹50L life cover", "Online-only no commission", "Nominee gets full payout"],
      "cons": ["Pays nothing if alive", "No chronic condition coverage", "No hospital bills paid"]
  },
  {
      "id": 13,
      "name": "Max Bupa Heartbeat",
      "insurer": "Max Bupa",
      "type": "Comprehensive",
      "annual_premium": 15000,
      "coverage": 3000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [40, 26.0, 2000000, 1500, 0, 5.6, 125, 0, 0, 1],
      "pros": ["Maternity coverage included", "International treatments covered", "High limit"],
      "cons": ["Premium is on the higher side", "Maternity has 2-year waiting period"]
  },
  {
      "id": 14,
      "name": "SBI General Arogya Premier",
      "insurer": "SBI General",
      "type": "Standard",
      "annual_premium": 10500,
      "coverage": 1000000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 0,
      "max_age": 65,
      "ideal_vector": [38, 25.0, 900000, 1100, 0, 5.5, 122, 0, 0, 0],
      "pros": ["SBI trust factor", "Wide network in tier-2/3 cities", "Automatic reinstatement"],
      "cons": ["Slower claims processing", "No Day 1 covers for chronic"]
  },
  {
      "id": 15,
      "name": "Religare Health Care Freedom",
      "insurer": "Care Health (Religare)",
      "type": "Senior",
      "annual_premium": 19500,
      "coverage": 500000,
      "pre_existing_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "min_age": 50,
      "max_age": 85,
      "ideal_vector": [70, 26.0, 500000, 2000, 0, 6.5, 140, 1, 1, 2],
      "pros": ["No pre-policy medical checkup", "Covers up to age 85", "Domiciliary care"],
      "cons": ["Co-payment of 20% on all claims", "Low coverage for the price"]
  }
]
