INSURANCE_PLANS = [
  {
      "id": 1,
      "name": "Arogya Sanjeevani",
      "insurer": "Star Health",
      "type": "Basic",
      "annual_premium": 3600,
      "coverage": 500000,
      "preexisting_wait_years": 4,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": False,
      "mental_health": False,
      "opd": False,
      "air_ambulance": False,
      "min_age": 0,
      "max_age": 65,
      "pros": ["Cheapest premium", "9,800+ hospitals", "No medical test under 45"],
      "cons": ["4-year pre-existing wait", "Low coverage ceiling", "No restore benefit"]
  },
  {
      "id": 2,
      "name": "HDFC Optima Secure",
      "insurer": "HDFC ERGO",
      "type": "Comprehensive",
      "annual_premium": 8200,
      "coverage": 1000000,
      "preexisting_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": True,
      "mental_health": True,
      "opd": False,
      "air_ambulance": False,
      "min_age": 0,
      "max_age": 65,
      "pros": ["Restore benefit", "50% no-claim bonus", "Mental health covered"],
      "cons": ["2-year pre-existing wait", "No OPD cover"]
  },
  {
      "id": 3,
      "name": "Star Health Diabetes Safe",
      "insurer": "Star Health",
      "type": "Comprehensive",
      "annual_premium": 14000,
      "coverage": 500000,
      "preexisting_wait_years": 0,
      "diabetes_day1": True,
      "hypertension_day1": True,
      "restore": False,
      "mental_health": False,
      "opd": True,
      "air_ambulance": False,
      "min_age": 0,
      "max_age": 65,
      "pros": ["Diabetes covered from Day 1", "Hypertension Day 1", "OPD included"],
      "cons": ["Designed for diabetic patients only", "Lower coverage limit"]
  },
  {
      "id": 4,
      "name": "Niva Bupa ReAssure 2.0",
      "insurer": "Niva Bupa",
      "type": "Comprehensive",
      "annual_premium": 11500,
      "coverage": 2500000,
      "preexisting_wait_years": 1,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": True,
      "mental_health": True,
      "opd": False,
      "air_ambulance": False,
      "min_age": 0,
      "max_age": 65,
      "pros": ["Only 1-year pre-existing wait", "₹25L coverage", "Mental health + unlimited restore"],
      "cons": ["Diabetes still has 1-year wait", "Higher premium"]
  },
  {
      "id": 5,
      "name": "Care Health Care Supreme",
      "insurer": "Care Health",
      "type": "Comprehensive",
      "annual_premium": 9800,
      "coverage": 1500000,
      "preexisting_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": True,
      "mental_health": False,
      "opd": False,
      "air_ambulance": True,
      "min_age": 0,
      "max_age": 75,
      "pros": ["Covers till age 75", "Annual health checkup", "Air ambulance"],
      "cons": ["2-year pre-existing wait", "Complex claims process"]
  },
  {
      "id": 6,
      "name": "LIC Arogya Rakshak",
      "insurer": "LIC",
      "type": "Senior",
      "annual_premium": 18000,
      "coverage": 1000000,
      "preexisting_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": False,
      "mental_health": False,
      "opd": False,
      "air_ambulance": False,
      "min_age": 45,
      "max_age": 80,
      "pros": ["Covers till 80", "LIC brand trust", "Critical illness rider"],
      "cons": ["Expensive", "Smaller hospital network", "Not available under 45"]
  },
  {
      "id": 7,
      "name": "Bajaj Allianz Health Guard",
      "insurer": "Bajaj Allianz",
      "type": "Standard",
      "annual_premium": 7200,
      "coverage": 750000,
      "preexisting_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": False,
      "mental_health": False,
      "opd": False,
      "air_ambulance": False,
      "min_age": 0,
      "max_age": 65,
      "pros": ["Affordable", "540 day-care procedures", "Large hospital network"],
      "cons": ["No restore benefit", "Limited OPD"]
  },
  {
      "id": 8,
      "name": "ICICI Lombard Complete Health",
      "insurer": "ICICI Lombard",
      "type": "Standard",
      "annual_premium": 8800,
      "coverage": 1000000,
      "preexisting_wait_years": 2,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": False,
      "mental_health": False,
      "opd": False,
      "air_ambulance": False,
      "min_age": 0,
      "max_age": 65,
      "pros": ["97% claim settlement ratio", "Telemedicine included", "Wellness rewards"],
      "cons": ["Standard 2-year wait", "Nothing exceptional for chronic conditions"]
  },
  {
      "id": 9,
      "name": "Aditya Birla Activ One",
      "insurer": "Aditya Birla",
      "type": "Comprehensive",
      "annual_premium": 13200,
      "coverage": 2000000,
      "preexisting_wait_years": 1,
      "diabetes_day1": False,
      "hypertension_day1": False,
      "restore": True,
      "mental_health": True,
      "opd": True,
      "air_ambulance": False,
      "min_age": 0,
      "max_age": 65,
      "pros": ["Fitness discount up to 10%", "OPD up to ₹15,000/year", "Only 1-year pre-existing wait"],
      "cons": ["Fitness tracking mandatory for discount", "Higher premium"]
  },
  {
      "id": 10,
      "name": "ManipalCigna Prime Senior",
      "insurer": "ManipalCigna",
      "type": "Senior",
      "annual_premium": 22000,
      "coverage": 2500000,
      "preexisting_wait_years": 0,
      "diabetes_day1": False,
      "hypertension_day1": True,
      "restore": True,
      "mental_health": False,
      "opd": False,
      "air_ambulance": False,
      "min_age": 56,
      "max_age": 80,
      "pros": ["Hypertension from Day 1", "₹25L coverage", "Home care included"],
      "cons": ["Only for 56+", "Diabetes still 1-year wait", "Most expensive"]
  }
]
